{
  inputs,
  nixpkgs,
  system,
}:
let
  pkgs = nixpkgs.legacyPackages.${system};

  # Wrapper so the repo script runs with awk/coreutils/grep on PATH — including
  # inside the pre-commit sandbox used by `nix flake check`.
  noctaliaScrub = pkgs.writeShellScriptBin "noctalia-scrub" ''
    export PATH="${pkgs.gawk}/bin:${pkgs.coreutils}/bin:${pkgs.gnugrep}/bin:$PATH"
    exec ${pkgs.bash}/bin/bash ${./scripts/noctalia-scrub.sh} "$@"
  '';

  check = inputs.git-hooks.lib.${system}.run {
    src = ./.;
    hooks = {
      nixfmt.enable = true;
      # -L / noLambdaPatternNames: keep lambda pattern names, otherwise deadnix
      # would delete the args that `callPackage` injects into the derivations
      # (e.g. modules/niri/niri-zoom.nix).
      deadnix = {
        enable = true;
        settings.noLambdaPatternNames = true;
      };
      statix = {
        enable = true;
        # Auto-generated by nixos-generate-config; not ours to lint.
        settings.ignore = [ "hosts/*/hardware-configuration.nix" ];
      };
      # The tracked Noctalia baseline must not contain secret fields (api_key, …).
      noctalia-scrub = {
        enable = true;
        name = "noctalia-scrub";
        entry = "${noctaliaScrub}/bin/noctalia-scrub --check";
        files = "\\.toml$";
        pass_filenames = false;
      };
      # Catch-all secret scanner: catches any secret, not just the known fields.
      ripsecrets.enable = true;
      # Validate TOML syntax (the exported Noctalia baseline among others).
      check-toml.enable = true;
      # Catch PEM private-key headers ("-----BEGIN ... PRIVATE KEY-----").
      detect-private-keys.enable = true;
    };
  };
in
{
  # `nix flake check` builds this; it also evaluates nixosConfigurations.
  checks = {
    pre-commit-check = check;
  };

  # `nix develop` (or the .envrc via direnv) installs the git hook.
  devShells = {
    default = pkgs.mkShell {
      inherit (check) shellHook enabledPackages;
    };
  };
}
