# New-host template.
# Copy this directory to hosts/<new>/ and replace <new> with the real
# hostname (here and in flake.nix nixosConfigurations), then run
# scripts/provision.sh <new> <disk> from the NixOS installer.
#
# hardware-configuration.nix is generated by scripts/provision.sh.
{ ... }: {
  imports = [
    ./disk-config.nix
    ./hardware-configuration.nix
  ];

  networking.hostName = "<new>";
}
