# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    "/home" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

    "/nix" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

    "/var/log" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

    "/.snapshots" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/mnt/very-hard-drive" = {
      device = "/dev/disk/by-label/very-hard-drive";
      fsType = "btrfs";
      options = [
        "defaults"
        "nofail"
        "compress=zstd"
      ];
    };

    "/mnt/games" = {
      device = "/dev/disk/by-label/games";
      fsType = "btrfs";
      options = [
        "defaults"
        "nofail"
        "compress=zstd"
      ];
    };

    "/mnt/old-ssd-2" = {
      device = "/dev/disk/by-label/old-ssd-2";
      fsType = "ntfs3";
      options = [
        "defaults"
        "nofail"
        "uid=1000"
        "gid=100"
        "rw"
      ];
    };

    "/mnt/old-ssd" = {
      device = "/dev/disk/by-label/old-ssd";
      fsType = "ntfs3";
      options = [
        "defaults"
        "nofail"
        "uid=1000"
        "gid=100"
        "rw"
      ];
    };

    "/mnt/cachyos-drive" = {
      device = "/dev/disk/by-label/cachyos-drive";
      fsType = "btrfs";
      options = [
        "defaults"
        "nofail"
        "compress=zstd"
      ]; # compress=zstd makes it faster and saves space
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
