color0 #000000
color1 #ff0000
color2 #aaaaaa
color3 #cccccc
color4 #aaaaaa
color5 #bbbbbb
color6 #aaaaaa
color7 #eeeeee
color8 #444444
color9 #ff0000
color10 #cccccc
color11 #dddddd
color12 #bbbbbb
color13 #dddddd
color14 #bbbbbb
color15 #ffffff

cursor                #ff0000
cursor_text_color     #000000
background            #000000
foreground            #eeeeee
selection_foreground  #ffffff
selection_background  #333333
active_border_color   #bb0000
inactive_border_color #000000
url_color             #bb0000

active_tab_foreground   #000000
active_tab_background   #bb0000
inactive_tab_foreground #cccccc
inactive_tab_background #000000
cursor_trail_color      #cccccc
